# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureFileCopy@6
  inputs:
    SourcePath: '*.json'
    azureSubscription: 'Visual Studio Enterprise Subscription (20ccd567-1ffd-428b-949d-089c504d45eb)'
    Destination: 'AzureBlob'
    storage: 'stfluentsearch'
    ContainerName: 'fluent-search'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Hotmail Visual Studio Subscription'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az afd endpoint purge -g rg-fluentsearch --profile-name fluentsearch-cdn --endpoint-name fluentsearch-cdn --content-paths ''/*'' --no-wait'